/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import javax.swing.JOptionPane;

/**
 *
 * @author x16472486
 */
public class BarGUI extends javax.swing.JFrame{

    /**
     * Creates new form BarGUI
     */
    public BarGUI() {
        initComponents();
        totalCost =0.00; 
        heineken = 5.50;
        carlsberg = 5.00;
        orchard = 4.50;
        guinness = 4.30;
        bulmers = 4.60;
        kopparberg = 5.80;
        spirits = 7.20;
        softDrink = 4.20;
        whiteWine = 5.50;
        redWine = 5.60;
        burger = 6.00;
        hotDog = 5.50;
        chips = 2.20;
        cashGiven=0.00;
        cashOwed=0.00;
    }
    private double totalCost;
    private final double heineken;
    private final double carlsberg;
    private final double orchard;
    private final double guinness;
    private final double bulmers;
    private final double kopparberg;
    private final double spirits;
    private final double softDrink;
    private final double whiteWine;
    private final double redWine;
    private final double burger;
    private final double hotDog;
    private final double chips;
    private double cashGiven;
    private double cashOwed;
    
    //Amount variables for log
    private int heinekenSold;
    private int carlsbergSold;
    private int orchardSold;
    private int guinnessSold;
    private int bulmersSold;
    private int kopparbergSold;
    private int vodkaSold;
    private int ginSold;
    private int whiskeySold;
    private int rumSold;
    private int tequilaSold;
    private int whiteWineSold;
    private int redWineSold;
    private int cokeSold;
    private int fantaSold;
    private int dietCokeSold;
    private int spriteSold;
    private int pepsiSold;
    private int hotDogSold;
    private int chipsSold;
    private int burgerSold;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        tequilaBtn = new javax.swing.JButton();
        spiritsLbl = new javax.swing.JLabel();
        carlsbergLbl = new javax.swing.JButton();
        chipsBtn = new javax.swing.JButton();
        tcostLbl = new javax.swing.JLabel();
        barLbl = new javax.swing.JLabel();
        ciderLbl = new javax.swing.JLabel();
        heinekenBtn = new javax.swing.JButton();
        redBtn = new javax.swing.JButton();
        amountTF = new javax.swing.JTextField();
        kopparbergBtn = new javax.swing.JButton();
        beerLbl = new javax.swing.JLabel();
        bulmersBtn = new javax.swing.JButton();
        dietcBtn = new javax.swing.JButton();
        tCostOutLbl = new javax.swing.JLabel();
        hotdBtn = new javax.swing.JButton();
        changeBtn = new javax.swing.JButton();
        spriteBtn = new javax.swing.JButton();
        whiskeyBtn = new javax.swing.JButton();
        changeLbl = new javax.swing.JLabel();
        vodkaBtn = new javax.swing.JButton();
        amountLbl = new javax.swing.JLabel();
        fantaBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        softLbl = new javax.swing.JLabel();
        burgerBtn = new javax.swing.JButton();
        rumBtn = new javax.swing.JButton();
        guinnessLbl = new javax.swing.JButton();
        foodLbl = new javax.swing.JLabel();
        orchardBtn = new javax.swing.JButton();
        ginBtn = new javax.swing.JButton();
        whiteBtn = new javax.swing.JButton();
        changeOutLbl = new javax.swing.JLabel();
        pepsiBtn = new javax.swing.JButton();
        cokeBtn = new javax.swing.JButton();
        wineLbl = new javax.swing.JLabel();
        amountOwedLbl = new javax.swing.JLabel();
        amountOwedOutLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 5000));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 3700));

        tequilaBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tequilaBtn.setText("Tequila");
        tequilaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tequilaBtnActionPerformed(evt);
            }
        });

        spiritsLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        spiritsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spiritsLbl.setText("Spirits");

        carlsbergLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        carlsbergLbl.setText("Carlsberg");
        carlsbergLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carlsbergLblActionPerformed(evt);
            }
        });

        chipsBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chipsBtn.setText("Chips");
        chipsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chipsBtnActionPerformed(evt);
            }
        });

        tcostLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tcostLbl.setText("Total Cost:");

        barLbl.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        barLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barLbl.setText("Bar");

        ciderLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        ciderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ciderLbl.setText("Cider");

        heinekenBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        heinekenBtn.setText("Heineken");
        heinekenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heinekenBtnActionPerformed(evt);
            }
        });

        redBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        redBtn.setText("Red wine");
        redBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redBtnActionPerformed(evt);
            }
        });

        amountTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountTF.setText("(Enter amount)");

        kopparbergBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kopparbergBtn.setText("Kopparberg");
        kopparbergBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kopparbergBtnActionPerformed(evt);
            }
        });

        beerLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        beerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        beerLbl.setText("Beer");

        bulmersBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bulmersBtn.setText("Bulmers");
        bulmersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulmersBtnActionPerformed(evt);
            }
        });

        dietcBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dietcBtn.setText("Diet Coke");
        dietcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietcBtnActionPerformed(evt);
            }
        });

        hotdBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hotdBtn.setText("Hot Dog");
        hotdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotdBtnActionPerformed(evt);
            }
        });

        changeBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        changeBtn.setText("Calculate Change");
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });

        spriteBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        spriteBtn.setText("Sprite");
        spriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteBtnActionPerformed(evt);
            }
        });

        whiskeyBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        whiskeyBtn.setText("Whiskey");
        whiskeyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiskeyBtnActionPerformed(evt);
            }
        });

        changeLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        changeLbl.setText("Change Due:");

        vodkaBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vodkaBtn.setText("Vodka");
        vodkaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vodkaBtnActionPerformed(evt);
            }
        });

        amountLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountLbl.setText("Cash Given:");

        fantaBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fantaBtn.setText("Fanta");
        fantaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        softLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        softLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        softLbl.setText("Soft Drinks");

        burgerBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        burgerBtn.setText("Burger");
        burgerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerBtnActionPerformed(evt);
            }
        });

        rumBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rumBtn.setText("Rum");
        rumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rumBtnActionPerformed(evt);
            }
        });

        guinnessLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        guinnessLbl.setText("Guinness");
        guinnessLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guinnessLblActionPerformed(evt);
            }
        });

        foodLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        foodLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodLbl.setText("Food");

        orchardBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orchardBtn.setText("Orchard Thieves");
        orchardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orchardBtnActionPerformed(evt);
            }
        });

        ginBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ginBtn.setText("Gin");
        ginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ginBtnActionPerformed(evt);
            }
        });

        whiteBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        whiteBtn.setText("White wine");
        whiteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteBtnActionPerformed(evt);
            }
        });

        pepsiBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pepsiBtn.setText("Pepsi");
        pepsiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiBtnActionPerformed(evt);
            }
        });

        cokeBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cokeBtn.setText("Coke");
        cokeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeBtnActionPerformed(evt);
            }
        });

        wineLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        wineLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wineLbl.setText("Wine");

        amountOwedLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountOwedLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountOwedLbl.setText("Change Owed:");

        amountOwedOutLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountOwedOutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(redBtn)
                                        .addGap(159, 159, 159)
                                        .addComponent(whiteBtn))
                                    .addComponent(whiskeyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(heinekenBtn)
                                        .addComponent(orchardBtn)
                                        .addComponent(vodkaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(burgerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(fantaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(82, 82, 82))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(dietcBtn)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(guinnessLbl)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bulmersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tequilaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(364, 364, 364))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(pepsiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cokeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(hotdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(161, 161, 161)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spriteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kopparbergBtn)
                                            .addComponent(carlsbergLbl)
                                            .addComponent(ginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(chipsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(52, 52, 52))))))
                    .addComponent(foodLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(softLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wineLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spiritsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ciderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(amountLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addComponent(changeBtn))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(239, 239, 239)
                                        .addComponent(changeLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(changeOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(299, 299, 299)
                                        .addComponent(amountOwedLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(amountOwedOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(306, 306, 306)
                                        .addComponent(tcostLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(tCostOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(150, 150, 150)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(barLbl)
                        .addGap(50, 50, 50)
                        .addComponent(beerLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heinekenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guinnessLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carlsbergLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71)
                .addComponent(ciderLbl)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orchardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bulmersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kopparbergBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(spiritsLbl)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vodkaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whiskeyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tequilaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(wineLbl)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whiteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(softLbl)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fantaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spriteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepsiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dietcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(foodLbl)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burgerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chipsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcostLbl)
                    .addComponent(tCostOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountOwedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountOwedOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 753, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeLbl)
                            .addComponent(changeOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 569, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 2287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1707, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void heinekenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heinekenBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+heineken;
        tCostOutLbl.setText(String.valueOf(totalCost));
        heinekenSold=heinekenSold+1;
    }//GEN-LAST:event_heinekenBtnActionPerformed

    private void orchardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orchardBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+orchard;
        tCostOutLbl.setText(String.valueOf(totalCost));
        orchardSold=orchardSold+1;
    }//GEN-LAST:event_orchardBtnActionPerformed

    private void guinnessLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guinnessLblActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+guinness;
        tCostOutLbl.setText(String.valueOf(totalCost));
    }//GEN-LAST:event_guinnessLblActionPerformed

    private void carlsbergLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carlsbergLblActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+carlsberg;
        tCostOutLbl.setText(String.valueOf(totalCost));
        carlsbergSold=carlsbergSold+1;
    }//GEN-LAST:event_carlsbergLblActionPerformed

    private void bulmersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulmersBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+bulmers;
        tCostOutLbl.setText(String.valueOf(totalCost));
        bulmersSold=bulmersSold+1;
    }//GEN-LAST:event_bulmersBtnActionPerformed

    private void kopparbergBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kopparbergBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+kopparberg;
        tCostOutLbl.setText(String.valueOf(totalCost));
        kopparbergSold=kopparbergSold+1;
    }//GEN-LAST:event_kopparbergBtnActionPerformed

    private void rumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rumBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(String.valueOf(totalCost));
        rumSold=rumSold+1;
    }//GEN-LAST:event_rumBtnActionPerformed

    private void vodkaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vodkaBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(String.valueOf(totalCost));
        vodkaSold=vodkaSold+1;
    }//GEN-LAST:event_vodkaBtnActionPerformed

    private void ginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ginBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(String.valueOf(totalCost));
        ginSold=ginSold+1;
    }//GEN-LAST:event_ginBtnActionPerformed

    private void whiskeyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiskeyBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(String.valueOf(totalCost));
        whiskeySold=whiskeySold+1;
    }//GEN-LAST:event_whiskeyBtnActionPerformed

    private void tequilaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tequilaBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(String.valueOf(totalCost));
        tequilaSold=tequilaSold+1;
    }//GEN-LAST:event_tequilaBtnActionPerformed

    private void fantaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(String.valueOf(totalCost));
        fantaSold=fantaSold+1;
        System.out.println(totalCost);
    }//GEN-LAST:event_fantaBtnActionPerformed

    private void whiteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+whiteWine;
        tCostOutLbl.setText(String.valueOf(totalCost));
        whiteWineSold=whiteWineSold+1;
    }//GEN-LAST:event_whiteBtnActionPerformed

    private void redBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+redWine;
        tCostOutLbl.setText(String.valueOf(totalCost));
        redWineSold=redWineSold+1;
    }//GEN-LAST:event_redBtnActionPerformed

    private void cokeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+softDrink;
        tCostOutLbl.setText(String.valueOf(totalCost));
        cokeSold=cokeSold+1;
        System.out.println(totalCost);
    }//GEN-LAST:event_cokeBtnActionPerformed

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        // TODO add your handling code here:
      double cashGiven = Double.parseDouble(amountTF.getText());  
      cashOwed=cashGiven-totalCost;
      amountOwedOutLbl.setText(String.valueOf(cashOwed));
    }//GEN-LAST:event_changeBtnActionPerformed

    private void spriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteBtnActionPerformed
        // TODO add your handling code here:
         totalCost=totalCost+softDrink;
        tCostOutLbl.setText(String.valueOf(totalCost));
        spriteSold=spriteSold+1;
        System.out.println(totalCost);
    }//GEN-LAST:event_spriteBtnActionPerformed

    private void dietcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietcBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+softDrink;
        tCostOutLbl.setText(String.valueOf(totalCost));
        dietCokeSold=dietCokeSold+1;
        System.out.println(totalCost);
    }//GEN-LAST:event_dietcBtnActionPerformed

    private void pepsiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+softDrink;
        tCostOutLbl.setText(String.valueOf(totalCost));
        pepsiSold=pepsiSold+1;
        System.out.println(totalCost);
    }//GEN-LAST:event_pepsiBtnActionPerformed

    private void burgerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerBtnActionPerformed
        // TODO add your handling code here:
         totalCost=totalCost+burger;
        tCostOutLbl.setText(String.valueOf(totalCost));
        burgerSold=burgerSold+1;
    }//GEN-LAST:event_burgerBtnActionPerformed

    private void hotdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotdBtnActionPerformed
        // TODO add your handling code here:
         totalCost=totalCost+hotDog;
        tCostOutLbl.setText(String.valueOf(totalCost));
        hotDogSold=hotDogSold+1;
    }//GEN-LAST:event_hotdBtnActionPerformed

    private void chipsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chipsBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+chips;
        tCostOutLbl.setText(String.valueOf(totalCost));
        chipsSold=chipsSold+1;
    }//GEN-LAST:event_chipsBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        amountTF.setText("(Enter Amount)");
        tCostOutLbl.setText("");
        changeOutLbl.setText("");
        totalCost=0.00;
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLbl;
    private javax.swing.JLabel amountOwedLbl;
    private javax.swing.JLabel amountOwedOutLbl;
    private javax.swing.JTextField amountTF;
    private javax.swing.JLabel barLbl;
    private javax.swing.JLabel beerLbl;
    private javax.swing.JButton bulmersBtn;
    private javax.swing.JButton burgerBtn;
    private javax.swing.JButton carlsbergLbl;
    private javax.swing.JButton changeBtn;
    private javax.swing.JLabel changeLbl;
    private javax.swing.JLabel changeOutLbl;
    private javax.swing.JButton chipsBtn;
    private javax.swing.JLabel ciderLbl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton cokeBtn;
    private javax.swing.JButton dietcBtn;
    private javax.swing.JButton fantaBtn;
    private javax.swing.JLabel foodLbl;
    private javax.swing.JButton ginBtn;
    private javax.swing.JButton guinnessLbl;
    private javax.swing.JButton heinekenBtn;
    private javax.swing.JButton hotdBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kopparbergBtn;
    private javax.swing.JButton orchardBtn;
    private javax.swing.JButton pepsiBtn;
    private javax.swing.JButton redBtn;
    private javax.swing.JButton rumBtn;
    private javax.swing.JLabel softLbl;
    private javax.swing.JLabel spiritsLbl;
    private javax.swing.JButton spriteBtn;
    private javax.swing.JLabel tCostOutLbl;
    private javax.swing.JLabel tcostLbl;
    private javax.swing.JButton tequilaBtn;
    private javax.swing.JButton vodkaBtn;
    private javax.swing.JButton whiskeyBtn;
    private javax.swing.JButton whiteBtn;
    private javax.swing.JLabel wineLbl;
    // End of variables declaration//GEN-END:variables
}
