/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 *  BarGUI.java
 * 
 *  Rev 4
 *
 *  02/12/2017

 * @author Eoin Kirwan, x16472486
 *
 */

public class BarGUI extends javax.swing.JFrame{

    /**
     * Creates new form BarGUI
     */
    public BarGUI() {
        
         try{
        inFile= new File ("Bar-Transaction-Log.txt");
        fr = new FileReader(inFile);
        br = new BufferedReader(fr);
        
        String[] items = new String[100];
        String line = "";
        int i=0;
        while(line!=null){
            line=br.readLine();
            items[i]=line;
            i=i+1;
        }
        br.close();
        heinekenSold=Integer.parseInt(items[0]);
        carlsbergSold=Integer.parseInt(items[1]);
        orchardSold=Integer.parseInt(items[2]);
        guinnessSold=Integer.parseInt(items[3]);
        bulmersSold=Integer.parseInt(items[4]);
        kopparbergSold=Integer.parseInt(items[5]);
        vodkaSold=Integer.parseInt(items[6]);
        ginSold=Integer.parseInt(items[7]);
        whiskeySold=Integer.parseInt(items[8]);
        rumSold=Integer.parseInt(items[9]);
        tequilaSold=Integer.parseInt(items[10]);
        whiteWineSold=Integer.parseInt(items[11]);
        redWineSold=Integer.parseInt(items[12]);
        cokeSold=Integer.parseInt(items[13]);
        fantaSold=Integer.parseInt(items[14]);
        dietCokeSold=Integer.parseInt(items[15]);
        spriteSold=Integer.parseInt(items[16]);
        pepsiSold=Integer.parseInt(items[17]);
        hotDogSold=Integer.parseInt(items[18]);
        chipsSold=Integer.parseInt(items[19]);
        burgerSold=Integer.parseInt(items[20]);
        taxOwed=Double.parseDouble(items[21]);
        
         }
         catch(IOException e){
         JOptionPane.showMessageDialog(null, "Sorry, there was an error reading from the file, please try closing and opening the application again "+e);
    
          }
         
        initComponents();
        totalCost =0.00; 
        heineken = 5.50;
        carlsberg = 5.00;
        orchard = 4.50;
        guinness = 4.30;
        bulmers = 4.60;
        kopparberg = 5.80;
        spirits = 7.20;
        softDrink = 4.0;
        whiteWine = 5.50;
        redWine = 5.60;
        burger = 6.00;
        hotDog = 5.50;
        chips = 2.20;
        cashGiven=0.00;
        cashOwed=0.00;
        taxRate=22.00;
        EURO = "\u20AC";
    }
    private double totalCost;
    private final double heineken;
    private final double carlsberg;
    private final double orchard;
    private final double guinness;
    private final double bulmers;
    private final double kopparberg;
    private final double spirits;
    private final double softDrink;
    private final double whiteWine;
    private final double redWine;
    private final double burger;
    private final double hotDog;
    private final double chips;
    private double cashGiven;
    private double cashOwed;
    private final String EURO;
    private JFrame frame;
    
    //Amount variables for log
    private int heinekenSold;
    private int carlsbergSold;
    private int orchardSold;
    private int guinnessSold;
    private int bulmersSold;
    private int kopparbergSold;
    private int vodkaSold;
    private int ginSold;
    private int whiskeySold;
    private int rumSold;
    private int tequilaSold;
    private int whiteWineSold;
    private int redWineSold;
    private int cokeSold;
    private int fantaSold;
    private int dietCokeSold;
    private int spriteSold;
    private int pepsiSold;
    private int hotDogSold;
    private int chipsSold;
    private int burgerSold;
    private double taxOwed;
    private double taxRate;
    
    DecimalFormat df = new DecimalFormat("#.##");
    
    File inFile;
    FileReader fr;
    BufferedReader br;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tequilaBtn = new javax.swing.JButton();
        spiritsLbl = new javax.swing.JLabel();
        carlsbergLbl = new javax.swing.JButton();
        chipsBtn = new javax.swing.JButton();
        tcostLbl = new javax.swing.JLabel();
        barLbl = new javax.swing.JLabel();
        ciderLbl = new javax.swing.JLabel();
        heinekenBtn = new javax.swing.JButton();
        redBtn = new javax.swing.JButton();
        amountTF = new javax.swing.JTextField();
        kopparbergBtn = new javax.swing.JButton();
        beerLbl = new javax.swing.JLabel();
        bulmersBtn = new javax.swing.JButton();
        dietcBtn = new javax.swing.JButton();
        tCostOutLbl = new javax.swing.JLabel();
        hotdBtn = new javax.swing.JButton();
        changeBtn = new javax.swing.JButton();
        spriteBtn = new javax.swing.JButton();
        whiskeyBtn = new javax.swing.JButton();
        changeLbl = new javax.swing.JLabel();
        vodkaBtn = new javax.swing.JButton();
        amountLbl = new javax.swing.JLabel();
        fantaBtn = new javax.swing.JButton();
        softLbl = new javax.swing.JLabel();
        burgerBtn = new javax.swing.JButton();
        rumBtn = new javax.swing.JButton();
        guinnessLbl = new javax.swing.JButton();
        foodLbl = new javax.swing.JLabel();
        orchardBtn = new javax.swing.JButton();
        ginBtn = new javax.swing.JButton();
        whiteBtn = new javax.swing.JButton();
        changeOutLbl = new javax.swing.JLabel();
        pepsiBtn = new javax.swing.JButton();
        cokeBtn = new javax.swing.JButton();
        wineLbl = new javax.swing.JLabel();
        amountOwedLbl = new javax.swing.JLabel();
        amountOwedOutLbl = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 3700));

        tequilaBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tequilaBtn.setText("Tequila");
        tequilaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tequilaBtnActionPerformed(evt);
            }
        });

        spiritsLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        spiritsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spiritsLbl.setText("Spirits");

        carlsbergLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        carlsbergLbl.setText("Carlsberg");
        carlsbergLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carlsbergLblActionPerformed(evt);
            }
        });

        chipsBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chipsBtn.setText("Chips");
        chipsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chipsBtnActionPerformed(evt);
            }
        });

        tcostLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tcostLbl.setText("Total Cost:");

        barLbl.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        barLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bar.png"))); // NOI18N

        ciderLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        ciderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ciderLbl.setText("Cider");

        heinekenBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        heinekenBtn.setText("Heineken");
        heinekenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heinekenBtnActionPerformed(evt);
            }
        });

        redBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        redBtn.setText("Red wine");
        redBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redBtnActionPerformed(evt);
            }
        });

        amountTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountTF.setText("(Enter amount)");

        kopparbergBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kopparbergBtn.setText("Kopparberg");
        kopparbergBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kopparbergBtnActionPerformed(evt);
            }
        });

        beerLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        beerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        beerLbl.setText("Beer");

        bulmersBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bulmersBtn.setText("Bulmers");
        bulmersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulmersBtnActionPerformed(evt);
            }
        });

        dietcBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dietcBtn.setText("Diet Coke");
        dietcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietcBtnActionPerformed(evt);
            }
        });

        tCostOutLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tCostOutLbl.setText("€ 0.00");

        hotdBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hotdBtn.setText("Hot Dog");
        hotdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotdBtnActionPerformed(evt);
            }
        });

        changeBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        changeBtn.setText("Calculate Change");
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });

        spriteBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        spriteBtn.setText("Sprite");
        spriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteBtnActionPerformed(evt);
            }
        });

        whiskeyBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        whiskeyBtn.setText("Whiskey");
        whiskeyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiskeyBtnActionPerformed(evt);
            }
        });

        changeLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        changeLbl.setText("Change Due:");

        vodkaBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vodkaBtn.setText("Vodka");
        vodkaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vodkaBtnActionPerformed(evt);
            }
        });

        amountLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountLbl.setText("Cash Given:");

        fantaBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fantaBtn.setText("Fanta");
        fantaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaBtnActionPerformed(evt);
            }
        });

        softLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        softLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        softLbl.setText("Soft Drinks");

        burgerBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        burgerBtn.setText("Burger");
        burgerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerBtnActionPerformed(evt);
            }
        });

        rumBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rumBtn.setText("Rum");
        rumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rumBtnActionPerformed(evt);
            }
        });

        guinnessLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        guinnessLbl.setText("Guinness");
        guinnessLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guinnessLblActionPerformed(evt);
            }
        });

        foodLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        foodLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodLbl.setText("Food");

        orchardBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orchardBtn.setText("Orchard Thieves");
        orchardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orchardBtnActionPerformed(evt);
            }
        });

        ginBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ginBtn.setText("Gin");
        ginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ginBtnActionPerformed(evt);
            }
        });

        whiteBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        whiteBtn.setText("White wine");
        whiteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteBtnActionPerformed(evt);
            }
        });

        pepsiBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pepsiBtn.setText("Pepsi");
        pepsiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiBtnActionPerformed(evt);
            }
        });

        cokeBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cokeBtn.setText("Coke");
        cokeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeBtnActionPerformed(evt);
            }
        });

        wineLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        wineLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wineLbl.setText("Wine");

        amountOwedLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountOwedLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountOwedLbl.setText("Change Owed:");

        amountOwedOutLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amountOwedOutLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        amountOwedOutLbl.setText("€ 0.00");

        clearBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        viewBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        viewBtn.setText("View Log");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heinekenBtn)
                            .addComponent(vodkaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cokeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(amountLbl)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(384, 384, 384)
                                .addComponent(tcostLbl)
                                .addGap(18, 18, 18)
                                .addComponent(tCostOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(burgerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addComponent(changeBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(amountOwedLbl)
                                        .addGap(14, 14, 14)
                                        .addComponent(amountOwedOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearBtn)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(hotdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(chipsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(viewBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(exitBtn))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spiritsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wineLbl)
                                .addGap(212, 212, 212))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(dietcBtn)
                                .addGap(29, 29, 29)
                                .addComponent(pepsiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(fantaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(spriteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(whiskeyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(rumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(tequilaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(132, 132, 132)
                                        .addComponent(whiteBtn)
                                        .addGap(57, 57, 57)
                                        .addComponent(redBtn))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(guinnessLbl)
                                        .addGap(35, 35, 35)
                                        .addComponent(carlsbergLbl)
                                        .addGap(200, 200, 200)
                                        .addComponent(orchardBtn)
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ciderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(bulmersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(kopparbergBtn)))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(softLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(foodLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(beerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(changeLbl)
                        .addGap(18, 18, 18)
                        .addComponent(changeOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(barLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(barLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(beerLbl)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ciderLbl)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heinekenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guinnessLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carlsbergLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orchardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bulmersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kopparbergBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spiritsLbl)
                    .addComponent(wineLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vodkaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whiskeyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tequilaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whiteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(softLbl)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foodLbl)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cokeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dietcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pepsiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fantaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spriteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(burgerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chipsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2858, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeLbl)
                            .addComponent(changeOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcostLbl)
                            .addComponent(tCostOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountOwedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountOwedOutLbl)
                            .addComponent(clearBtn)
                            .addComponent(viewBtn)
                            .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(681, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "+---------------------------------------------------+\n"
            +"|                             Beer                               \n"
            +"|----------------------------------------------------|\n"
            +"| Heineken sold: " +heinekenSold
            +"\n"+"| Carlsberg sold: "+carlsbergSold
            +"\n"+"| Guinness sold: "+guinnessSold
            +"\n"+"+---------------------------------------------------+\n"
            +"|                             Cider                              \n"
            +"|----------------------------------------------------|\n"
            +"| Bulmers sold: "+bulmersSold
            +"\n"+"| Orchard thieves sold: "+orchardSold
            +"\n"+"| Kopparberg sold: "+kopparbergSold
            +"\n"+"+---------------------------------------------------+\n"
            +"|                             Spirits                            \n"
            +"|----------------------------------------------------|\n"
            +"| Vodka sold: "+vodkaSold
            +"\n"+"| Gin sold: "+ginSold
            +"\n"+"| Whiksey sold: "+whiskeySold
            +"\n"+"| Rum sold: "+rumSold
            +"\n"+"| Tequila sold: "+tequilaSold
            +"\n"+"+---------------------------------------------------+\n"
            +"|                             Wine                               \n"
            +"|----------------------------------------------------|\n"
            +"| White wine sold: "+whiteWineSold
            +"\n"+"| Red wine sold: "+redWineSold
            +"\n"+"+---------------------------------------------------+\n"
            +"|                           Soft Drinks                      \n"
            +"|-----------------------------------------------------|\n"
            +"| Coke sold: "+cokeSold
            +"\n"+"| Fanta sold: "+fantaSold
            +"\n"+"| Diet coke sold: "+dietCokeSold
            +"\n"+"| Sprite sold: "+spriteSold
            +"\n"+"| Pepsi sold: "+pepsiSold
            +"\n"+"+---------------------------------------------------+\n"
            +"|                             Food                               \n"
            +"|----------------------------------------------------|\n"
            +"| Hot dogs sold: "+ginSold
            +"\n"+"| Chips sold: "+chipsSold
            +"\n"+"| Burgers sold: "+burgerSold
                +"\n"+"+---------------------------------------------------+\n"
            +"|                             Tax                              \n"
            +"|----------------------------------------------------|\n"
            +"| Total Tax Owed: "+EURO+" "+df.format(taxOwed)
             +"\n"+"|----------------------------------------------------|\n"

        );
    }//GEN-LAST:event_viewBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        amountTF.setText("(Enter Amount)");
        tCostOutLbl.setText(EURO+" "+"0.00");
        amountOwedOutLbl.setText(EURO+" "+"0.00");
        totalCost=0.00;

    }//GEN-LAST:event_clearBtnActionPerformed

    private void cokeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+softDrink;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        cokeSold=cokeSold+1;
    }//GEN-LAST:event_cokeBtnActionPerformed

    private void pepsiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+softDrink;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        pepsiSold=pepsiSold+1;
    }//GEN-LAST:event_pepsiBtnActionPerformed

    private void whiteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+whiteWine;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        whiteWineSold=whiteWineSold+1;
    }//GEN-LAST:event_whiteBtnActionPerformed

    private void ginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ginBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        ginSold=ginSold+1;
    }//GEN-LAST:event_ginBtnActionPerformed

    private void orchardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orchardBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+orchard;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        orchardSold=orchardSold+1;
    }//GEN-LAST:event_orchardBtnActionPerformed

    private void guinnessLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guinnessLblActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+guinness;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        guinnessSold=guinnessSold+1;
    }//GEN-LAST:event_guinnessLblActionPerformed

    private void rumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rumBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        rumSold=rumSold+1;
    }//GEN-LAST:event_rumBtnActionPerformed

    private void burgerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+burger;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        burgerSold=burgerSold+1;
    }//GEN-LAST:event_burgerBtnActionPerformed

    private void fantaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+softDrink;

        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        fantaSold=fantaSold+1;
    }//GEN-LAST:event_fantaBtnActionPerformed

    private void vodkaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vodkaBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        vodkaSold=vodkaSold+1;
    }//GEN-LAST:event_vodkaBtnActionPerformed

    private void whiskeyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiskeyBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        whiskeySold=whiskeySold+1;
    }//GEN-LAST:event_whiskeyBtnActionPerformed

    private void spriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+softDrink;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        spriteSold=spriteSold+1;
    }//GEN-LAST:event_spriteBtnActionPerformed

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        // TODO add your handling code here:
        double cashGiven = Double.parseDouble(amountTF.getText());
        if(totalCost<=cashGiven){
        cashOwed=cashGiven-totalCost;
        amountOwedOutLbl.setText(EURO+" "+String.valueOf(df.format(cashOwed)));
        taxOwed=taxOwed+(totalCost*taxRate)/100;

        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        try{
            outFile = new File ("Bar-Transaction-Log.txt");
            fw = new FileWriter(outFile);
            bw = new BufferedWriter(fw);

            bw.write(String.valueOf(heinekenSold));
            bw.newLine();
            bw.write(String.valueOf(carlsbergSold));
            bw.newLine();
            bw.write(String.valueOf(orchardSold));
            bw.newLine();
            bw.write(String.valueOf(guinnessSold));
            bw.newLine();
            bw.write(String.valueOf(bulmersSold));
            bw.newLine();
            bw.write(String.valueOf(kopparbergSold));
            bw.newLine();
            bw.write(String.valueOf(vodkaSold));
            bw.newLine();
            bw.write(String.valueOf(ginSold));
            bw.newLine();
            bw.write(String.valueOf(whiskeySold));
            bw.newLine();
            bw.write(String.valueOf(rumSold));
            bw.newLine();
            bw.write(String.valueOf(tequilaSold));
            bw.newLine();
            bw.write(String.valueOf(whiteWineSold));
            bw.newLine();
            bw.write(String.valueOf(redWineSold));
            bw.newLine();
            bw.write(String.valueOf(cokeSold));
            bw.newLine();
            bw.write(String.valueOf(fantaSold));
            bw.newLine();
            bw.write(String.valueOf(dietCokeSold));
            bw.newLine();
            bw.write(String.valueOf(spriteSold));
            bw.newLine();
            bw.write(String.valueOf(pepsiSold));
            bw.newLine();
            bw.write(String.valueOf(hotDogSold));
            bw.newLine();
            bw.write(String.valueOf(chipsSold));
            bw.newLine();
            bw.write(String.valueOf(burgerSold));
            bw.newLine();
            bw.write(String.valueOf(df.format(taxOwed)));
            

            bw.close();
            System.out.println("Saved to file successfully");
        }catch (IOException e){
            System.out.println("Error writing to file:"+e);
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "You have not entered enough money!");
        }
    }//GEN-LAST:event_changeBtnActionPerformed

    private void hotdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotdBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+hotDog;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        hotDogSold=hotDogSold+1;
    }//GEN-LAST:event_hotdBtnActionPerformed

    private void dietcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietcBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+softDrink;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        dietCokeSold=dietCokeSold+1;
    }//GEN-LAST:event_dietcBtnActionPerformed

    private void bulmersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulmersBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+bulmers;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        bulmersSold=bulmersSold+1;
    }//GEN-LAST:event_bulmersBtnActionPerformed

    private void kopparbergBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kopparbergBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+kopparberg;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        kopparbergSold=kopparbergSold+1;
    }//GEN-LAST:event_kopparbergBtnActionPerformed

    private void redBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+redWine;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        redWineSold=redWineSold+1;
    }//GEN-LAST:event_redBtnActionPerformed

    private void heinekenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heinekenBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+heineken;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        heinekenSold=heinekenSold+1;
    }//GEN-LAST:event_heinekenBtnActionPerformed

    private void chipsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chipsBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+chips;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        chipsSold=chipsSold+1;
    }//GEN-LAST:event_chipsBtnActionPerformed

    private void carlsbergLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carlsbergLblActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+carlsberg;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        carlsbergSold=carlsbergSold+1;
    }//GEN-LAST:event_carlsbergLblActionPerformed

    private void tequilaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tequilaBtnActionPerformed
        // TODO add your handling code here:
        totalCost=totalCost+spirits;
        tCostOutLbl.setText(EURO+" "+String.valueOf(df.format(totalCost)));
        tequilaSold=tequilaSold+1;
    }//GEN-LAST:event_tequilaBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit"); // Creates object
        if(JOptionPane.showConfirmDialog(frame, "Do you want to exit?", "Bar", 
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){              
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BarGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLbl;
    private javax.swing.JLabel amountOwedLbl;
    private javax.swing.JLabel amountOwedOutLbl;
    private javax.swing.JTextField amountTF;
    private javax.swing.JLabel barLbl;
    private javax.swing.JLabel beerLbl;
    private javax.swing.JButton bulmersBtn;
    private javax.swing.JButton burgerBtn;
    private javax.swing.JButton carlsbergLbl;
    private javax.swing.JButton changeBtn;
    private javax.swing.JLabel changeLbl;
    private javax.swing.JLabel changeOutLbl;
    private javax.swing.JButton chipsBtn;
    private javax.swing.JLabel ciderLbl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton cokeBtn;
    private javax.swing.JButton dietcBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton fantaBtn;
    private javax.swing.JLabel foodLbl;
    private javax.swing.JButton ginBtn;
    private javax.swing.JButton guinnessLbl;
    private javax.swing.JButton heinekenBtn;
    private javax.swing.JButton hotdBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kopparbergBtn;
    private javax.swing.JButton orchardBtn;
    private javax.swing.JButton pepsiBtn;
    private javax.swing.JButton redBtn;
    private javax.swing.JButton rumBtn;
    private javax.swing.JLabel softLbl;
    private javax.swing.JLabel spiritsLbl;
    private javax.swing.JButton spriteBtn;
    private javax.swing.JLabel tCostOutLbl;
    private javax.swing.JLabel tcostLbl;
    private javax.swing.JButton tequilaBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JButton vodkaBtn;
    private javax.swing.JButton whiskeyBtn;
    private javax.swing.JButton whiteBtn;
    private javax.swing.JLabel wineLbl;
    // End of variables declaration//GEN-END:variables
}
