/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrew McBride
 */
public class RestaurantGUI extends javax.swing.JFrame {
    double nachos = 5.99;
    double chickenWings = 6.00;
    double onionRings = 5.99;
    double soup = 5.50;
    double grilledChickenBurger = 9.25;
    double veggieBurger = 8.99;
    double baconCheeseBurger = 9.50;
    double doubleBeefBurger = 9.25;
    double buffaloChickenWrap = 8.25;
    double roastTurkeyWrap = 8.75;
    double phillyCheeseSteak = 7.99;
    double coffee = 2.50;
    double tea = 2.50;
    double orangeJuice = 2.15;
    double water = 1.00;
    double taxRate = 3.7;
    double subTotal, total, change, tax, cost;  // Variables declared for calulation
    double[] itemCost = new double[14]; // Array declared for calculating each item

    /**
     * Creates new form RestaurantGUI
     */
    public RestaurantGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblRestaurant = new javax.swing.JLabel();
        jlblBurgerMeal = new javax.swing.JLabel();
        jchkNachos = new javax.swing.JCheckBox();
        jchkChickenWings = new javax.swing.JCheckBox();
        jchkOnionRings = new javax.swing.JCheckBox();
        jchkSoup = new javax.swing.JCheckBox();
        jlblSandwichMeal = new javax.swing.JLabel();
        jtxtNachos = new javax.swing.JTextField();
        jtxtChickenWings = new javax.swing.JTextField();
        jtxtOnionRings = new javax.swing.JTextField();
        jtxtSoup = new javax.swing.JTextField();
        jchkGrilledChickenBurger = new javax.swing.JCheckBox();
        jchkVeggieBurger = new javax.swing.JCheckBox();
        jchkBaconCheeseBurger = new javax.swing.JCheckBox();
        jchkDoubleBeefBurger = new javax.swing.JCheckBox();
        jtxtGrilledChickenBurger = new javax.swing.JTextField();
        jtxtVeggieBurger = new javax.swing.JTextField();
        jtxtBaconCheeseBurger = new javax.swing.JTextField();
        jtxtDoubleBeefBurger = new javax.swing.JTextField();
        jlblStarters = new javax.swing.JLabel();
        jchkBuffaloChickenWrap = new javax.swing.JCheckBox();
        jchkPhillyCheeseSteak = new javax.swing.JCheckBox();
        jchkRoastTurkeyWrap = new javax.swing.JCheckBox();
        jtxtBuffaloChickenWrap = new javax.swing.JTextField();
        jtxtPhillyCheeseSteak = new javax.swing.JTextField();
        jtxtRoastTurkeyWrap = new javax.swing.JTextField();
        jlblDrinks = new javax.swing.JLabel();
        jchkCoffee = new javax.swing.JCheckBox();
        jchkTea = new javax.swing.JCheckBox();
        jchkOrangeJuice = new javax.swing.JCheckBox();
        jchkWater = new javax.swing.JCheckBox();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtTea = new javax.swing.JTextField();
        jtxtOrangeJuice = new javax.swing.JTextField();
        jtxtWater = new javax.swing.JTextField();
        jlblPayment = new javax.swing.JLabel();
        jcomboPayment = new javax.swing.JComboBox<>();
        jtxtPayment = new javax.swing.JTextField();
        jbtnTotal = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jlblChange = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jlblTax = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jlblSubTotal = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblRestaurant.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblRestaurant.setText("Restaurant");

        jlblBurgerMeal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblBurgerMeal.setText("Burger Meal");

        jchkNachos.setText("Nachos     £5.99");
        jchkNachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkNachosActionPerformed(evt);
            }
        });

        jchkChickenWings.setText("Chicken Wings     £6.00");
        jchkChickenWings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkChickenWingsActionPerformed(evt);
            }
        });

        jchkOnionRings.setText("Onion Rings     £5.99");
        jchkOnionRings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkOnionRingsActionPerformed(evt);
            }
        });

        jchkSoup.setText("Soup     £5.50");
        jchkSoup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSoupActionPerformed(evt);
            }
        });

        jlblSandwichMeal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblSandwichMeal.setText("Sandwich Meal");

        jtxtNachos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtNachos.setText("0");
        jtxtNachos.setEnabled(false);
        jtxtNachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNachosActionPerformed(evt);
            }
        });
        jtxtNachos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNachosKeyTyped(evt);
            }
        });

        jtxtChickenWings.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenWings.setText("0");
        jtxtChickenWings.setEnabled(false);
        jtxtChickenWings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChickenWingsKeyTyped(evt);
            }
        });

        jtxtOnionRings.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtOnionRings.setText("0");
        jtxtOnionRings.setEnabled(false);
        jtxtOnionRings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtOnionRingsKeyTyped(evt);
            }
        });

        jtxtSoup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSoup.setText("0");
        jtxtSoup.setEnabled(false);
        jtxtSoup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSoupActionPerformed(evt);
            }
        });
        jtxtSoup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSoupKeyTyped(evt);
            }
        });

        jchkGrilledChickenBurger.setText("Grilled Chicken Burger     £9.25");
        jchkGrilledChickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkGrilledChickenBurgerActionPerformed(evt);
            }
        });

        jchkVeggieBurger.setText("Veggie Burger     £8.99");
        jchkVeggieBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkVeggieBurgerActionPerformed(evt);
            }
        });

        jchkBaconCheeseBurger.setText("Bacon Cheese Burger     £9.50");
        jchkBaconCheeseBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkBaconCheeseBurgerActionPerformed(evt);
            }
        });

        jchkDoubleBeefBurger.setText("Double Beef Burger     £9.25");
        jchkDoubleBeefBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkDoubleBeefBurgerActionPerformed(evt);
            }
        });

        jtxtGrilledChickenBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtGrilledChickenBurger.setText("0");
        jtxtGrilledChickenBurger.setEnabled(false);
        jtxtGrilledChickenBurger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtGrilledChickenBurgerKeyTyped(evt);
            }
        });

        jtxtVeggieBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVeggieBurger.setText("0");
        jtxtVeggieBurger.setEnabled(false);
        jtxtVeggieBurger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtVeggieBurgerKeyTyped(evt);
            }
        });

        jtxtBaconCheeseBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBaconCheeseBurger.setText("0");
        jtxtBaconCheeseBurger.setEnabled(false);
        jtxtBaconCheeseBurger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBaconCheeseBurgerKeyTyped(evt);
            }
        });

        jtxtDoubleBeefBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtDoubleBeefBurger.setText("0");
        jtxtDoubleBeefBurger.setEnabled(false);
        jtxtDoubleBeefBurger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDoubleBeefBurgerKeyTyped(evt);
            }
        });

        jlblStarters.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblStarters.setText("Starters");

        jchkBuffaloChickenWrap.setText("Buffalo Chicken Wrap     £8.25");
        jchkBuffaloChickenWrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkBuffaloChickenWrapActionPerformed(evt);
            }
        });

        jchkPhillyCheeseSteak.setText("Philly Cheese Steak     £7.99");
        jchkPhillyCheeseSteak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkPhillyCheeseSteakActionPerformed(evt);
            }
        });

        jchkRoastTurkeyWrap.setText("Roast Turkey Wrap     £8.75");
        jchkRoastTurkeyWrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkRoastTurkeyWrapActionPerformed(evt);
            }
        });

        jtxtBuffaloChickenWrap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBuffaloChickenWrap.setText("0");
        jtxtBuffaloChickenWrap.setEnabled(false);
        jtxtBuffaloChickenWrap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBuffaloChickenWrapKeyTyped(evt);
            }
        });

        jtxtPhillyCheeseSteak.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPhillyCheeseSteak.setText("0");
        jtxtPhillyCheeseSteak.setEnabled(false);
        jtxtPhillyCheeseSteak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPhillyCheeseSteakKeyTyped(evt);
            }
        });

        jtxtRoastTurkeyWrap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRoastTurkeyWrap.setText("0");
        jtxtRoastTurkeyWrap.setEnabled(false);
        jtxtRoastTurkeyWrap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtRoastTurkeyWrapKeyTyped(evt);
            }
        });

        jlblDrinks.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblDrinks.setText("Drinks");

        jchkCoffee.setText("Coffee     £2.50");
        jchkCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCoffeeActionPerformed(evt);
            }
        });

        jchkTea.setText("Tea     £2.50");
        jchkTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkTeaActionPerformed(evt);
            }
        });

        jchkOrangeJuice.setText("Orange Juice     £2.15");
        jchkOrangeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkOrangeJuiceActionPerformed(evt);
            }
        });

        jchkWater.setText("Water     £1.00");
        jchkWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkWaterActionPerformed(evt);
            }
        });

        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.setEnabled(false);
        jtxtCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCoffeeKeyTyped(evt);
            }
        });

        jtxtTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTea.setText("0");
        jtxtTea.setEnabled(false);
        jtxtTea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTeaKeyTyped(evt);
            }
        });

        jtxtOrangeJuice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtOrangeJuice.setText("0");
        jtxtOrangeJuice.setEnabled(false);
        jtxtOrangeJuice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtOrangeJuiceKeyTyped(evt);
            }
        });

        jtxtWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtWater.setText("0");
        jtxtWater.setEnabled(false);
        jtxtWater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtWaterKeyTyped(evt);
            }
        });

        jlblPayment.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlblPayment.setText("Payment");

        jcomboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit Card", "Credit Card" }));
        jcomboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboPaymentActionPerformed(evt);
            }
        });

        jtxtPayment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPayment.setText("0");
        jtxtPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPaymentKeyTyped(evt);
            }
        });

        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jlblChange.setText("Change");

        jtxtChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblTax.setText("Tax");

        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblSubTotal.setText("Sub Total");

        jtxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlblTotal.setText("Total");

        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jchkDoubleBeefBurger)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxtDoubleBeefBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jchkBaconCheeseBurger)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxtBaconCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jchkVeggieBurger)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxtVeggieBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchkSoup)
                                            .addComponent(jchkChickenWings)
                                            .addComponent(jchkNachos)
                                            .addComponent(jchkOnionRings))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtNachos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtChickenWings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtOnionRings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtSoup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jchkGrilledChickenBurger)
                                        .addGap(27, 27, 27)
                                        .addComponent(jtxtGrilledChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jcomboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)))
                        .addComponent(jlblChange))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnReset)
                        .addGap(70, 70, 70)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkRoastTurkeyWrap)
                            .addComponent(jchkPhillyCheeseSteak))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtRoastTurkeyWrap)
                            .addComponent(jtxtPhillyCheeseSteak)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jchkBuffaloChickenWrap)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtBuffaloChickenWrap, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchkCoffee)
                                    .addComponent(jchkTea)
                                    .addComponent(jchkOrangeJuice))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtOrangeJuice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtTea, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(jtxtWater)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jchkWater)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlblTotal)
                                    .addGap(21, 21, 21)))
                            .addComponent(jbtnExit))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblSubTotal)
                            .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jlblRestaurant)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblTax)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jlblBurgerMeal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblDrinks)
                .addGap(149, 149, 149))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jbtnTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jlblPayment)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal))
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jlblStarters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblSandwichMeal)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblRestaurant)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblStarters)
                    .addComponent(jlblSandwichMeal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jchkBuffaloChickenWrap)
                        .addComponent(jtxtBuffaloChickenWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtNachos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jchkNachos)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkChickenWings)
                    .addComponent(jchkRoastTurkeyWrap)
                    .addComponent(jtxtRoastTurkeyWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChickenWings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkOnionRings)
                    .addComponent(jtxtOnionRings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkPhillyCheeseSteak)
                    .addComponent(jtxtPhillyCheeseSteak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkSoup)
                    .addComponent(jtxtSoup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblBurgerMeal)
                    .addComponent(jlblDrinks))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkGrilledChickenBurger)
                    .addComponent(jtxtGrilledChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkCoffee)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkVeggieBurger)
                    .addComponent(jtxtVeggieBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkTea)
                    .addComponent(jtxtTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkBaconCheeseBurger)
                    .addComponent(jtxtBaconCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkOrangeJuice)
                    .addComponent(jtxtOrangeJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkDoubleBeefBurger)
                    .addComponent(jtxtDoubleBeefBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkWater)
                    .addComponent(jtxtWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jlblPayment)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcomboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblChange)
                        .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlblTax)
                        .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnTotal)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblSubTotal)
                        .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotal)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboPaymentActionPerformed
private JFrame frame; // Declare Variable JFrame
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit"); // Creates object
        if(JOptionPane.showConfirmDialog(frame, "Do you want to exit?", "Restaurant", // If exit button is pressed, a frame pops up with a yes or no option
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){              
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jtxtNachos.setText(null); // Sets textbox to null when btn pressed
        jtxtChickenWings.setText(null);
        jtxtOnionRings.setText(null);
        jtxtSoup.setText(null);
        jtxtGrilledChickenBurger.setText(null);
        jtxtVeggieBurger.setText(null);
        jtxtBaconCheeseBurger.setText(null);
        jtxtDoubleBeefBurger.setText(null);
        jtxtBuffaloChickenWrap.setText(null);
        jtxtRoastTurkeyWrap.setText(null);
        jtxtPhillyCheeseSteak.setText(null);
        jtxtCoffee.setText(null);
        jtxtTea.setText(null);
        jtxtOrangeJuice.setText(null);
        jtxtWater.setText(null);
        jtxtPayment.setText(null);
        
        jchkNachos.setSelected(false); // Unselects checkbox that are checked
        jchkChickenWings.setSelected(false);
        jchkOnionRings.setSelected(false);
        jchkSoup.setSelected(false);
        jchkGrilledChickenBurger.setSelected(false);
        jchkVeggieBurger.setSelected(false);
        jchkBaconCheeseBurger.setSelected(false);
        jchkDoubleBeefBurger.setSelected(false);
        jchkBuffaloChickenWrap.setSelected(false);
        jchkRoastTurkeyWrap.setSelected(false);
        jchkPhillyCheeseSteak.setSelected(false);
        jchkCoffee.setSelected(false);
        jchkTea.setSelected(false);
        jchkOrangeJuice.setSelected(false);
        jchkWater.setSelected(false);
        
        
        
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtNachosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNachosKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtNachosKeyTyped

    private void jtxtChickenWingsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChickenWingsKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtChickenWingsKeyTyped

    private void jtxtOnionRingsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtOnionRingsKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtOnionRingsKeyTyped

    private void jtxtSoupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSoupKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtSoupKeyTyped

    private void jtxtGrilledChickenBurgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGrilledChickenBurgerKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtGrilledChickenBurgerKeyTyped

    private void jtxtVeggieBurgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtVeggieBurgerKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtVeggieBurgerKeyTyped

    private void jtxtBaconCheeseBurgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBaconCheeseBurgerKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtBaconCheeseBurgerKeyTyped

    private void jtxtDoubleBeefBurgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDoubleBeefBurgerKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtDoubleBeefBurgerKeyTyped

    private void jtxtBuffaloChickenWrapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuffaloChickenWrapKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtBuffaloChickenWrapKeyTyped

    private void jtxtRoastTurkeyWrapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtRoastTurkeyWrapKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtRoastTurkeyWrapKeyTyped

    private void jtxtPhillyCheeseSteakKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPhillyCheeseSteakKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtPhillyCheeseSteakKeyTyped

    private void jtxtCoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCoffeeKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtCoffeeKeyTyped

    private void jtxtTeaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTeaKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtTeaKeyTyped

    private void jtxtOrangeJuiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtOrangeJuiceKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtOrangeJuiceKeyTyped

    private void jtxtWaterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtWaterKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtWaterKeyTyped

    private void jtxtPaymentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPaymentKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // Declares char called iNumber
        if(!(Character.isDigit(iNumber)) // Only allows numbers to be entered
            || (iNumber == KeyEvent.VK_BACK_SPACE)
            || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtPaymentKeyTyped

    private void jchkNachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkNachosActionPerformed
        // TODO add your handling code here:
        if(jchkNachos.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtNachos.setEnabled(true);
            jtxtNachos.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtNachos.setEnabled(false);
            jtxtNachos.setText("0"); // Unchecked shows a 0
        }
        
    }//GEN-LAST:event_jchkNachosActionPerformed

    private void jchkChickenWingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkChickenWingsActionPerformed
        // TODO add your handling code here:
        if(jchkChickenWings.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtChickenWings.setEnabled(true);
            jtxtChickenWings.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtChickenWings.setEnabled(false);
        }
    }//GEN-LAST:event_jchkChickenWingsActionPerformed

    private void jchkOnionRingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkOnionRingsActionPerformed
        // TODO add your handling code here:
        if(jchkOnionRings.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtOnionRings.setEnabled(true);
            jtxtOnionRings.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtOnionRings.setEnabled(false);
        }
    }//GEN-LAST:event_jchkOnionRingsActionPerformed

    private void jchkSoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSoupActionPerformed
        // TODO add your handling code here:
        if(jchkSoup.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtSoup.setEnabled(true);
            jtxtSoup.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtSoup.setEnabled(false);
        }
    }//GEN-LAST:event_jchkSoupActionPerformed

    private void jchkGrilledChickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkGrilledChickenBurgerActionPerformed
        // TODO add your handling code here:
        if(jchkGrilledChickenBurger.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtGrilledChickenBurger.setEnabled(true);
            jtxtGrilledChickenBurger.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtGrilledChickenBurger.setEnabled(false);
        }
    }//GEN-LAST:event_jchkGrilledChickenBurgerActionPerformed

    private void jchkVeggieBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkVeggieBurgerActionPerformed
        // TODO add your handling code here:
        if(jchkVeggieBurger.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtVeggieBurger.setEnabled(true);
            jtxtVeggieBurger.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtVeggieBurger.setEnabled(false);
        }
    }//GEN-LAST:event_jchkVeggieBurgerActionPerformed

    private void jchkBaconCheeseBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkBaconCheeseBurgerActionPerformed
        // TODO add your handling code here:
        if(jchkBaconCheeseBurger.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtBaconCheeseBurger.setEnabled(true);
            jtxtBaconCheeseBurger.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtBaconCheeseBurger.setEnabled(false);
        }
    }//GEN-LAST:event_jchkBaconCheeseBurgerActionPerformed

    private void jchkDoubleBeefBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkDoubleBeefBurgerActionPerformed
        // TODO add your handling code here:
        if(jchkDoubleBeefBurger.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtDoubleBeefBurger.setEnabled(true);
            jtxtDoubleBeefBurger.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtDoubleBeefBurger.setEnabled(false);
        }
    }//GEN-LAST:event_jchkDoubleBeefBurgerActionPerformed

    private void jchkBuffaloChickenWrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkBuffaloChickenWrapActionPerformed
        // TODO add your handling code here:
        if(jchkBuffaloChickenWrap.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtBuffaloChickenWrap.setEnabled(true);
            jtxtBuffaloChickenWrap.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtBuffaloChickenWrap.setEnabled(false);
        }
    }//GEN-LAST:event_jchkBuffaloChickenWrapActionPerformed

    private void jchkRoastTurkeyWrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkRoastTurkeyWrapActionPerformed
        // TODO add your handling code here:
        if(jchkRoastTurkeyWrap.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtRoastTurkeyWrap.setEnabled(true);
            jtxtRoastTurkeyWrap.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtRoastTurkeyWrap.setEnabled(false);
        }
    }//GEN-LAST:event_jchkRoastTurkeyWrapActionPerformed

    private void jchkPhillyCheeseSteakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkPhillyCheeseSteakActionPerformed
        // TODO add your handling code here:
        if(jchkPhillyCheeseSteak.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtPhillyCheeseSteak.setEnabled(true);
            jtxtPhillyCheeseSteak.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtPhillyCheeseSteak.setEnabled(false);
        }
    }//GEN-LAST:event_jchkPhillyCheeseSteakActionPerformed

    private void jchkCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCoffeeActionPerformed
        // TODO add your handling code here:
        if(jchkCoffee.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtCoffee.setEnabled(true);
            jtxtCoffee.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtCoffee.setEnabled(false);
        }
    }//GEN-LAST:event_jchkCoffeeActionPerformed

    private void jchkTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkTeaActionPerformed
        // TODO add your handling code here:
        if(jchkTea.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtTea.setEnabled(true);
            jtxtTea.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtTea.setEnabled(false);
        }
    }//GEN-LAST:event_jchkTeaActionPerformed

    private void jchkOrangeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkOrangeJuiceActionPerformed
        // TODO add your handling code here:
        if(jchkOrangeJuice.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtOrangeJuice.setEnabled(true);
            jtxtOrangeJuice.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtOrangeJuice.setEnabled(false);
        }
    }//GEN-LAST:event_jchkOrangeJuiceActionPerformed

    private void jchkWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkWaterActionPerformed
        // TODO add your handling code here:
        if(jchkWater.isSelected()) //If chk box selected, text field is enabled
        {
            jtxtWater.setEnabled(true);
            jtxtWater.setText(""); // Checked txt box shows nothing
        }
        else{
            jtxtWater.setEnabled(false);
        }
    }//GEN-LAST:event_jchkWaterActionPerformed

    private void jtxtNachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNachosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNachosActionPerformed

    private void jtxtSoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSoupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSoupActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        itemCost[0] = Double.parseDouble(jtxtNachos.getName()); // Stores number inserted from txtbox as array [0]
        itemCost[1] = Double.parseDouble(jtxtChickenWings.getName()); // parse returns double value represented by string
        itemCost[2] = Double.parseDouble(jtxtOnionRings.getName());
        itemCost[3] = Double.parseDouble(jtxtSoup.getName());
        itemCost[4] = Double.parseDouble(jtxtGrilledChickenBurger.getName());
        itemCost[5] = Double.parseDouble(jtxtVeggieBurger.getName());
        itemCost[6] = Double.parseDouble(jtxtBaconCheeseBurger.getName());
        itemCost[7] = Double.parseDouble(jtxtDoubleBeefBurger.getName());
        itemCost[8] = Double.parseDouble(jtxtBuffaloChickenWrap.getName());
        itemCost[9] = Double.parseDouble(jtxtRoastTurkeyWrap.getName());
        itemCost[10] = Double.parseDouble(jtxtPhillyCheeseSteak.getName());
        itemCost[11] = Double.parseDouble(jtxtCoffee.getName());
        itemCost[12] = Double.parseDouble(jtxtTea.getName());
        itemCost[13] = Double.parseDouble(jtxtOrangeJuice.getName());
        itemCost[14] = Double.parseDouble(jtxtWater.getName());
        
        change = Double.parseDouble(jtxtPayment.getText()); // Change var declared returns primitive doubele type
        
        String payment = (String) jcomboPayment.getSelectedItem(); // jcombo becomes a String
        
        if (payment == "cash"){ // If statement needed so each payment methods cash or card will show the endtax, endSubTotal and endTotal
        subTotal = itemCost[0] + itemCost[1] + itemCost[2] + itemCost[3] + itemCost[4] +// 
                   itemCost[5] + itemCost[6] + itemCost[7] + itemCost[8] + itemCost[9] +
                   itemCost[10] + itemCost[11] + itemCost[12] + itemCost[13] + itemCost[14];
        
        if(change >= subTotal){ // If statement for change added to only cash option
        
        tax = (subTotal * taxRate)/100;
        
        String endTax = String.format("£.2f", tax); // Declares string endTax that formats subtotal to pound sign and 2 decimal places
        jtxtTax.setText(endTax);                    // and stores tax in the txt box
        
        String endSubTotal = String.format("£.2f", subTotal); 
        jtxtSubTotal.setText(endSubTotal);                    
        
        String endTotal = String.format("£.2f", subTotal + taxRate); // Adds subTotal and taxRate
        jtxtTotal.setText(endTotal);
        
        String endChange = String.format("£.2f", change -(subTotal + taxRate));
        jtxtChange.setText(endChange);
        }
        else{
            JOptionPane.showMessageDialog(null, "You didn't enter enough cash", "Restaurant", JOptionPane.OK_CANCEL_OPTION); // Returns message pop-up stating that not
        }                                                                                                                    // enough was entered. Ok option added 
        }
        else if (payment == "Debit Card" || payment == "Credit Card")
        {
        subTotal = itemCost[0] + itemCost[1] + itemCost[2] + itemCost[3] + itemCost[4] +// 
                   itemCost[5] + itemCost[6] + itemCost[7] + itemCost[8] + itemCost[9] +
                   itemCost[10] + itemCost[11] + itemCost[12] + itemCost[13] + itemCost[14];
        
        tax = (subTotal * taxRate)/100;
        
        String endTax = String.format("£.2f", tax); // Declares string endTax that formats subtotal to pound sign and 2 decimal places
        jtxtTax.setText(endTax);                    // and stores tax in the txt box
        
        String endSubTotal = String.format("£.2f", subTotal); 
        jtxtSubTotal.setText(endSubTotal);                    
        
        String endTotal = String.format("£.2f", subTotal + taxRate); // Adds subTotal and taxRate
        jtxtTotal.setText(endTotal);   
        }
        else{
            JOptionPane.showMessageDialog(null, "You didn't enter enough cash", "Restaurant", JOptionPane.OK_CANCEL_OPTION);
        }
    }//GEN-LAST:event_jbtnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JCheckBox jchkBaconCheeseBurger;
    private javax.swing.JCheckBox jchkBuffaloChickenWrap;
    private javax.swing.JCheckBox jchkChickenWings;
    private javax.swing.JCheckBox jchkCoffee;
    private javax.swing.JCheckBox jchkDoubleBeefBurger;
    private javax.swing.JCheckBox jchkGrilledChickenBurger;
    private javax.swing.JCheckBox jchkNachos;
    private javax.swing.JCheckBox jchkOnionRings;
    private javax.swing.JCheckBox jchkOrangeJuice;
    private javax.swing.JCheckBox jchkPhillyCheeseSteak;
    private javax.swing.JCheckBox jchkRoastTurkeyWrap;
    private javax.swing.JCheckBox jchkSoup;
    private javax.swing.JCheckBox jchkTea;
    private javax.swing.JCheckBox jchkVeggieBurger;
    private javax.swing.JCheckBox jchkWater;
    private javax.swing.JComboBox<String> jcomboPayment;
    private javax.swing.JLabel jlblBurgerMeal;
    private javax.swing.JLabel jlblChange;
    private javax.swing.JLabel jlblDrinks;
    private javax.swing.JLabel jlblPayment;
    private javax.swing.JLabel jlblRestaurant;
    private javax.swing.JLabel jlblSandwichMeal;
    private javax.swing.JLabel jlblStarters;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextField jtxtBaconCheeseBurger;
    private javax.swing.JTextField jtxtBuffaloChickenWrap;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtChickenWings;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtDoubleBeefBurger;
    private javax.swing.JTextField jtxtGrilledChickenBurger;
    private javax.swing.JTextField jtxtNachos;
    private javax.swing.JTextField jtxtOnionRings;
    private javax.swing.JTextField jtxtOrangeJuice;
    private javax.swing.JTextField jtxtPayment;
    private javax.swing.JTextField jtxtPhillyCheeseSteak;
    private javax.swing.JTextField jtxtRoastTurkeyWrap;
    private javax.swing.JTextField jtxtSoup;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTea;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtVeggieBurger;
    private javax.swing.JTextField jtxtWater;
    // End of variables declaration//GEN-END:variables
}
